;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/SuperHeatedSteam/Content/Localization/SuperHeatedSteam
DestinationPath=Mods/GameFeatures/SuperHeatedSteam/Content/Localization/SuperHeatedSteam
ManifestName=SuperHeatedSteam.manifest
ArchiveName=SuperHeatedSteam.archive
ResourceName=SuperHeatedSteam.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
bValidateRichTextTags=false
NativeCulture=en
CulturesToGenerate=en

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

