;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
ManifestDependencies=Content/Localization/Game/Game.manifest
ManifestDependencies=Mods/SML/Content/Localization/SML/SML.manifest
SourcePath=Mods/GameFeatures/SuperHeatedSteam/Content/Localization/SuperHeatedSteam
DestinationPath=Mods/GameFeatures/SuperHeatedSteam/Content/Localization/SuperHeatedSteam
ManifestName=SuperHeatedSteam.manifest
ArchiveName=SuperHeatedSteam.archive
NativeCulture=en
CulturesToGenerate=en

[GatherTextStep0]
CommandletClass=GatherTextFromSource
SearchDirectoryPaths=%LOCPROJECTROOT%Mods/GameFeatures/SuperHeatedSteam/Config
ExcludePathFilters=Config/Localization/*
FileNameFilters=*.h
FileNameFilters=*.cpp
FileNameFilters=*.ini
ShouldGatherFromEditorOnlyData=false

[GatherTextStep1]
CommandletClass=GatherTextFromAssets
IncludePathFilters=%LOCPROJECTROOT%Mods/GameFeatures/SuperHeatedSteam/Content/*
ExcludePathFilters=Content/Localization/*
ExcludePathFilters=Content/L10N/*
PackageFileNameFilters=*.umap
PackageFileNameFilters=*.uasset
ShouldExcludeDerivedClasses=false
ShouldGatherFromEditorOnlyData=false
SkipGatherCache=false

[GatherTextStep2]
CommandletClass=GenerateGatherManifest

[GatherTextStep3]
CommandletClass=GenerateGatherArchive

[GatherTextStep4]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=SuperHeatedSteam.csv
bConflictReport=true
ConflictReportName=SuperHeatedSteam_Conflicts.txt

